on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rome
        uses: ./
        with:
          preview: true

      - name: Run Rome
        run: rome --help